spring:
  application:
    name: project

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  messages:
    basename: i18n/messages
    encoding: UTF-8


server:
  error:
    include-stacktrace: never
    include-message: always

security:
  rsa:
    public-key-path: ${RSA_PUBLIC_KEY}
    private-key-path: ${RSA_PRIVATE_KEY}

  auth:
    jwt:
      issuer: ${JWT_ISSUER}

    seed:
      admin-username: ${ADMIN_USERNAME}
      admin-password: ${ADMIN_PASSWORD}

      user-username: ${USER_USERNAME}
      user-password: ${USER_PASSWORD}

  cors:
    frontend: ${CORS_FRONTEND}

integration:
  s3:
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
